services:
  letta_db:
    image: pgvector/pgvector:pg17
    networks:
      default:
        aliases:
          - pgvector_db
          - letta-db
    environment:
      - POSTGRES_USER=${LETTA_PG_USER:-juan}
      - POSTGRES_PASSWORD=${LETTA_PG_PASSWORD:-juan}
      - POSTGRES_DB=${LETTA_PG_DB:-juan}
    volumes:
      - ./.persist/postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${LETTA_PG_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U juan"]
      interval: 10s
      timeout: 8s
      retries: 8
  letta_server:
    image: letta/letta:latest
    hostname: letta-server
    depends_on:
      letta_db:
        condition: service_healthy
    ports:
      - "8083:8083"
      - "8283:8283"
    env_file:
      - .env
    environment:
      - LETTA_PG_URI=${LETTA_PG_URI:-postgresql://${LETTA_PG_USER:-juan}:${LETTA_PG_PASSWORD:-juan}@${LETTA_DB_HOST:-letta-db}:${LETTA_PG_PORT:-5432}/${LETTA_PG_DB:-juan}}
      - LETTA_DEBUG=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - GROQ_API_KEY=${GROQ_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      # - AZURE_API_KEY=${AZURE_API_KEY}
      # - AZURE_BASE_URL=${AZURE_BASE_URL}
      # - AZURE_API_VERSION=${AZURE_API_VERSION}
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
      # - VLLM_API_BASE=${VLLM_API_BASE}
      # - OPENLLM_AUTH_TYPE=${OPENLLM_AUTH_TYPE}
      # - OPENLLM_API_KEY=${OPENLLM_API_KEY}
      # - LETTA_OTEL_EXPORTER_OTLP_ENDPOINT=${LETTA_OTEL_EXPORTER_OTLP_ENDPOINT}
      # - CLICKHOUSE_ENDPOINT=${CLICKHOUSE_ENDPOINT}
      # - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      # - CLICKHOUSE_USERNAME=${CLICKHOUSE_USERNAME}
      # - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    # volumes:
    # - ./configs/server_config.yaml:/root/.letta/config # config file
    # - ~/.letta/credentials:/root/.letta/credentials # credentials file
    # Uncomment this line to mount a local directory for tool execution, and specify the mount path
    # before running docker compose: `export LETTA_SANDBOX_MOUNT_PATH=$PWD/directory`
    # - ${LETTA_SANDBOX_MOUNT_PATH:?}:/root/.letta/tool_execution_dir # mounted volume for tool execution
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8283/v1/health/"]
      interval: 15s # How often the status will be checked
      retries: 8 # How many times to check before considering it unavailable
      start_period: 100s # How long after startup to begin checks
      timeout: 25s # Timeout for each test run
  letta_nginx:
    hostname: letta-nginx
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  endpoint_upload_doc:
    build: ./endpoint_upload_doc
    ports:
          - "5000:5000"
    depends_on:
      letta_server:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - letta_server
      - endpoint_upload_doc
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://endpoint_upload_doc:5000
      - NEXT_PUBLIC_LETTA_URL=http://letta_server:8283


